export const postsMocked = [{
  isPhoto: true,
  url: 'https://picsum.photos/1200',
  description: 'Ouais pas mal',
  user: { name: 'Thomas', username: 'N0roo', img: 'https://picsum.photos/50' },
  date: '2021-06-01',
  feed: 'Amis',
},
{
  isPhoto: true,
  url: 'https://picsum.photos/1201',
  description: 'Téma la vue',
  user: { name: 'Augustin', username: '10gust10', img: 'https://picsum.photos/51' },
  date: '2021-06-01',
  feed: 'Amis',
},
{
  isPhoto: true,
  url: 'https://picsum.photos/1202',
  description: "C'est ça qui me fallait",
  user: { name: 'Lorenzo', username: 'lorenzoavr_', img: 'https://picsum.photos/52' },
  date: '2021-06-01',
  feed: 'Amis',
},
{
  isPhoto: true,
  url: 'https://picsum.photos/1203',
  description: 'Si siii Ocho',
  user: { name: 'Félix', username: 'plix_panot', img: 'https://picsum.photos/53' },
  date: '2021-06-01',
  feed: 'Amis',
}];
