export const postsMocked = [{
  isPhoto: true,
  url: '/posts/totofun.JPG',
  description: 'Sacré crâne',
  user: { name: 'Thomas', username: 'N0roo', img: '/toto.jpeg' },
  date: '2021-06-01',
  feed: 'Amis',
},
{
  isPhoto: true,
  url: '/posts/augustin.JPG',
  description: 'Derkap de bz ce défi',
  user: { name: 'Augustin', username: '10gust10', img: '/aug.jpeg' },
  date: '2021-06-01',
  feed: 'Amis',
},
{
  isPhoto: true,
  url: '/posts/lorefun.JPG',
  description: "Avec le COAT",
  user: { name: 'Lorenzo', username: 'lorenzoavr_', img: '/lore.jpg' },
  date: '2021-06-01',
  feed: 'Amis',
},
{
  isPhoto: true,
  url: '/posts/felixfun.JPG',
  description: "Crane d'oeuf t'as peur",
  user: { name: 'Félix', username: 'plix_panot', img: '/pelix.jpeg' },
  date: '2021-06-01',
  feed: 'Amis',
}];
